//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList.Entity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoListItem
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public int Order { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
